name: 'Deploy Jugsaw Application'
description: 'Deploy jugsaw applications to the cloud!'
inputs:
  token:
    description: "The token to upload your application. You can find it in your profile page after logging in https://jugsaw.co"
    required: true
  registry:
    description: "The url endpoint of the Jugsaw registry server."
    required: false
    default: 'https://harbor.jugsaw.co'
  user:
    description: "The user name at Jugsaw. The repository owner's name is used by default."
    required: false
    default: ""
  app:
    description: "The name of the application to deploy. If not set, the value will be inferred from the basename of `github.workspace`."
    required: false
  dir:
    description: "The directory to the application source code"
    required: false
    default: ""
outputs:
  app:
    description: 'The id of the deployed applications (`user_name/app_name@sha256:xxx` ). An empty string is returned if an application is deployed unsuccessfully.'
    value: ${{ steps.deploy-to-jugsaw.outputs.app }}
runs:
  using: 'composite'
  steps:
    - id: gen-docker-file
      uses: Jugsaw/github-actions/extract-application-meta@develop
      with:
        dir: ${{ inputs.dir }}
    - id: extract-name
      run: |
        echo "app=`basename ${{ inputs.app || github.workspace }}`" >> $GITHUB_OUTPUT
        echo "user=${{ inputs.user || github.repository_owner }}" >> $GITHUB_OUTPUT
      shell: bash
    - id: deploy-to-jugsaw
      run: |
        echo "app=${{ steps.extract-name.outputs.user }}/${{ steps.extract-name.outputs.app }}@sha256:xxx" >> $GITHUB_OUTPUT
      shell: bash