name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: harbor.jugsaw.co
          username: ${{ secrets.JUGSAW_USERNAME }}
          password: ${{ secrets.JUGSAW_TOKEN }}
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date +%d-%m-%y_%T)" >> ${GITHUB_ENV}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jugsaw/${{ env.RELEASE_DATE }}
